import Countdown from "./Countdown";
import { eventData } from "./data";
export default function Home(){const{celebrants,venue,whatsapp}=eventData;const whatsappUrl=`https://wa.me/${whatsapp.number}?text=${encodeURIComponent(whatsapp.message)}`;return <main className="invitation" style={{"--background-image":`url(${eventData.backgroundImage})`}}>
<div className="hero"><div className="hero-image"/><div className="hero-overlay"/><header className="topbar"><span>FORTY · FORTY</span><span>2026</span></header>
<section className="hero-content"><p className="eyebrow">Una celebración para recordar</p><h1><span>{celebrants.person1}</span><i>&amp;</i><span>{celebrants.person2}</span></h1><div className="hero-rule"/><p className="big-number"><strong>40</strong><em>/</em><strong>40</strong></p><p className="hero-date">{eventData.displayDate}<br/><span>{eventData.displayTime}</span></p><Countdown targetDate={eventData.eventDate}/><a className="rsvp-button" href={whatsappUrl} target="_blank" rel="noreferrer"><img src={eventData.rsvpMeme} alt=""/><span>Sí autorizo</span><b>↗</b></a><span className="scroll-hint">SCROLL PARA DESCUBRIR ↓</span></section></div>
<section className="details-section"><div className="section-number">01</div><div className="details-heading"><p className="eyebrow dark">Los detalles </p></div><div className="details-grid">
<div className="detail"><small>FECHA</small><strong>{eventData.displayDate}</strong></div><div className="detail"><small>HORA DE INICIO</small><strong>{eventData.displayTime}</strong></div><div className="detail"><small>LUGAR</small><strong>{venue.name}</strong><p>{venue.address}</p></div><div className="detail"><small>DRESS CODE</small><strong>{eventData.dressCode}</strong></div></div><a className="maps-link" href={venue.mapsUrl} target="_blank" rel="noreferrer"><span>VER UBICACIÓN</span><b>↗</b></a></section>
<section className="rsvp-section"><div className="rsvp-inner"><p className="eyebrow dark">02 · RSVP</p><h2>¿Nos acompañas?</h2><p>Confirma tu asistencia por WhatsApp.<br/>Te esperamos para celebrar juntos.</p><a className="rsvp-final" href={whatsappUrl} target="_blank" rel="noreferrer"><img src={eventData.rsvpMeme} alt=""/><span>Sí autorizo</span><b>↗</b></a></div></section>
<footer><span>Hecho por Ivan isidro </span><span>Todos los derechos reservados, 2026</span></footer></main>}
